Document: azmq
Title: Debian azmq Manual
Author: <insert document author here>
Abstract: This manual describes what azmq is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/azmq/azmq.sgml.gz

Format: postscript
Files: /usr/share/doc/azmq/azmq.ps.gz

Format: text
Files: /usr/share/doc/azmq/azmq.text.gz

Format: HTML
Index: /usr/share/doc/azmq/html/index.html
Files: /usr/share/doc/azmq/html/*.html
